### ISSUE TITLE
Armature not matching to structure in blender

### ISSUE THREAD

**Issue by Bkhor48** [durrantlab/pyrite#1]
Hello! I am attempting to use the Pyrite add-on to export animations from Blender to Unity for a project I am working on. Unfortunately, I am running into an issue in Blender where the armature created by Pyrite is not mapping on to the .obj structure exported from VMD. I was able to use the example molecule and trajectory just fine, but when I attempted it with my own molecules I could not get it to work. This issue specifically occurs when I attempt to change the representation in VMD. The armature is able to map onto the "line" structure form from VMD, but it is unable to map onto any other representations I have attempted. Please let me know if this problem has been encountered or has a fix!

**Comment by jacobdurrant** [comment]
Thanks for your interest in Pyrite. It's been quite some time since I've looked at that code, so I'm happy to hear that it still works with more recent versions of Blender. I suspect what's happening is that the protein mesh generated using representations other than 'surface' places too many vertices far from the armature bones, making it impossible to properly map the bones to mesh points.

I wonder if you could map the bones to mesh points manually using settings other than the default. Because it's been a while since I've done animation in Blender, I'm not sure if the approach is exactly the same as it used to be, but hopefully that will at least get you started.

I should also mention that the [MolecularNodes Blender plugin](https://github.com/BradyAJohnston/MolecularNodes) can also read trajectories. It takes an entirely different approach, using Blender's new Geometry Node system. I've played around with it only a little bit, but it seems quite good. You might want to look into that as an alternative

Hope this is helpful.

Take care,
Jacob

**Comment by Bkhor48** [comment]
Wonderful! I really appreciate your help with this matter. I'll look into what you mentioned!

Best,
Boris

**Comment by jacobdurrant** [comment]
Happy to have helped! I'll go ahead and close this issue, but feel free to repoen it if needed. ~Jacob
